services:
  # --- PostgreSQL database ---
  db:
    image: postgres:16-alpine
    container_name: his_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: patient_registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kali
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - his_network

  # --- pgAdmin (Database GUI) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: his_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - his_network

networks:
  his_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: