FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY frontend/ /usr/share/nginx/html/

# Copy our custom nginx config, overriding the default
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80